substitutions:
  <<: !include secrets.yaml

  device_number: "01"
  device_unit: "electropulse1"
  device_board: "il1"
  device_version: "7.1.1"
  device_author: "ivanych"
  device_timezone: "Europe/Moscow"

packages:
  devices:
    url: https://github.com/ivanych/esphome-devices
    ref: ${device_version}
    files:
      - ${device_unit}_${device_board}.yaml

    #!include ../esphome-devices/${device_unit}_${device_board}.yaml
