substitutions:
  <<: !include secrets.yaml

  device_number: "01"
  device_unit: "relay7"
  device_board: "sdr3"
  device_version: "5.0.2"
  device_author: "ivanych"
  device_timezone: "Europe/Moscow"

packages:
  devices:
    url: https://github.com/ivanych/esphome-devices
    ref: ${device_version}
    files:
      - ${device_unit}_${device_board}.yaml
    #!include ../esphome-devices/${device_unit}_${device_board}.yaml
