substitutions:
  <<: !include secrets.yaml

  device_number: "03"
  device_author: "ivanych"
  device_unit: "relay4"
  device_board: "sp316"
  device_version: "3.0.0"
  device_timezone: "Europe/Moscow"

packages:
  devices: github://ivanych/esphome-devices/${device_unit}_${device_board}.yaml@${device_version}
  #devices: !include ../esphome-devices/${device_unit}_${device_board}.yaml
