substitutions:
  <<: !include secrets.yaml
  device_number: '03'

packages:
  devices: github://ivanych/esphome-devices/relay4_sp316.yaml@2.1.0
  #devices: !include ../esphome-devices/relay4_sp316.yaml
